<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AssistanceSchedulesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('assistance_schedules')->delete();
        
        \DB::table('assistance_schedules')->insert(array (
            0 => 
            array (
                'id' => 1,
                'charity_case_id' => 1,
                'assistance_type_id' => 1,
                'parent_schedule_id' => NULL,
                'scheduled_date' => '2026-04-20',
                'end_date' => '2026-04-30',
                'occurrence_number' => NULL,
                'scheduled_time' => NULL,
                'amount' => '500.00',
                'quantity' => NULL,
                'frequency' => 'daily',
                'status' => 'approved',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-17 23:59:53',
                'updated_at' => '2026-04-17 23:59:53',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'charity_case_id' => 1,
                'assistance_type_id' => 1,
                'parent_schedule_id' => 1,
                'scheduled_date' => '2026-04-21',
                'end_date' => NULL,
                'occurrence_number' => 1,
                'scheduled_time' => NULL,
                'amount' => '500.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-17 23:59:53',
                'updated_at' => '2026-04-17 23:59:53',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'charity_case_id' => 1,
                'assistance_type_id' => 1,
                'parent_schedule_id' => 1,
                'scheduled_date' => '2026-04-22',
                'end_date' => NULL,
                'occurrence_number' => 2,
                'scheduled_time' => NULL,
                'amount' => '500.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-17 23:59:53',
                'updated_at' => '2026-04-17 23:59:53',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'charity_case_id' => 1,
                'assistance_type_id' => 1,
                'parent_schedule_id' => 1,
                'scheduled_date' => '2026-04-23',
                'end_date' => NULL,
                'occurrence_number' => 3,
                'scheduled_time' => NULL,
                'amount' => '500.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-17 23:59:53',
                'updated_at' => '2026-04-17 23:59:53',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'charity_case_id' => 1,
                'assistance_type_id' => 1,
                'parent_schedule_id' => 1,
                'scheduled_date' => '2026-04-24',
                'end_date' => NULL,
                'occurrence_number' => 4,
                'scheduled_time' => NULL,
                'amount' => '500.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-17 23:59:53',
                'updated_at' => '2026-04-17 23:59:53',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'charity_case_id' => 1,
                'assistance_type_id' => 1,
                'parent_schedule_id' => 1,
                'scheduled_date' => '2026-04-25',
                'end_date' => NULL,
                'occurrence_number' => 5,
                'scheduled_time' => NULL,
                'amount' => '500.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-17 23:59:53',
                'updated_at' => '2026-04-17 23:59:53',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'charity_case_id' => 1,
                'assistance_type_id' => 1,
                'parent_schedule_id' => 1,
                'scheduled_date' => '2026-04-26',
                'end_date' => NULL,
                'occurrence_number' => 6,
                'scheduled_time' => NULL,
                'amount' => '500.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-17 23:59:53',
                'updated_at' => '2026-04-17 23:59:53',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'charity_case_id' => 1,
                'assistance_type_id' => 1,
                'parent_schedule_id' => 1,
                'scheduled_date' => '2026-04-27',
                'end_date' => NULL,
                'occurrence_number' => 7,
                'scheduled_time' => NULL,
                'amount' => '500.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-17 23:59:53',
                'updated_at' => '2026-04-17 23:59:53',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'charity_case_id' => 1,
                'assistance_type_id' => 1,
                'parent_schedule_id' => 1,
                'scheduled_date' => '2026-04-28',
                'end_date' => NULL,
                'occurrence_number' => 8,
                'scheduled_time' => NULL,
                'amount' => '500.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-17 23:59:53',
                'updated_at' => '2026-04-17 23:59:53',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'charity_case_id' => 1,
                'assistance_type_id' => 1,
                'parent_schedule_id' => 1,
                'scheduled_date' => '2026-04-29',
                'end_date' => NULL,
                'occurrence_number' => 9,
                'scheduled_time' => NULL,
                'amount' => '500.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-17 23:59:53',
                'updated_at' => '2026-04-17 23:59:53',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => NULL,
                'scheduled_date' => '2026-04-20',
                'end_date' => '2026-05-29',
                'occurrence_number' => NULL,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'daily',
                'status' => 'approved',
                'funding_status' => 'partially_funded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-04-21',
                'end_date' => NULL,
                'occurrence_number' => 1,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-04-22',
                'end_date' => NULL,
                'occurrence_number' => 2,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-04-23',
                'end_date' => NULL,
                'occurrence_number' => 3,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-04-24',
                'end_date' => NULL,
                'occurrence_number' => 4,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-04-25',
                'end_date' => NULL,
                'occurrence_number' => 5,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-04-26',
                'end_date' => NULL,
                'occurrence_number' => 6,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-04-27',
                'end_date' => NULL,
                'occurrence_number' => 7,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-04-28',
                'end_date' => NULL,
                'occurrence_number' => 8,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-04-29',
                'end_date' => NULL,
                'occurrence_number' => 9,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-04-30',
                'end_date' => NULL,
                'occurrence_number' => 10,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-01',
                'end_date' => NULL,
                'occurrence_number' => 11,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-02',
                'end_date' => NULL,
                'occurrence_number' => 12,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-03',
                'end_date' => NULL,
                'occurrence_number' => 13,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-04',
                'end_date' => NULL,
                'occurrence_number' => 14,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-05',
                'end_date' => NULL,
                'occurrence_number' => 15,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-06',
                'end_date' => NULL,
                'occurrence_number' => 16,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-07',
                'end_date' => NULL,
                'occurrence_number' => 17,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-08',
                'end_date' => NULL,
                'occurrence_number' => 18,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-09',
                'end_date' => NULL,
                'occurrence_number' => 19,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-10',
                'end_date' => NULL,
                'occurrence_number' => 20,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-11',
                'end_date' => NULL,
                'occurrence_number' => 21,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-12',
                'end_date' => NULL,
                'occurrence_number' => 22,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-13',
                'end_date' => NULL,
                'occurrence_number' => 23,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-14',
                'end_date' => NULL,
                'occurrence_number' => 24,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-15',
                'end_date' => NULL,
                'occurrence_number' => 25,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-16',
                'end_date' => NULL,
                'occurrence_number' => 26,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-17',
                'end_date' => NULL,
                'occurrence_number' => 27,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-18',
                'end_date' => NULL,
                'occurrence_number' => 28,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-19',
                'end_date' => NULL,
                'occurrence_number' => 29,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-20',
                'end_date' => NULL,
                'occurrence_number' => 30,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-21',
                'end_date' => NULL,
                'occurrence_number' => 31,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-22',
                'end_date' => NULL,
                'occurrence_number' => 32,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-23',
                'end_date' => NULL,
                'occurrence_number' => 33,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-24',
                'end_date' => NULL,
                'occurrence_number' => 34,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-25',
                'end_date' => NULL,
                'occurrence_number' => 35,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-26',
                'end_date' => NULL,
                'occurrence_number' => 36,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-27',
                'end_date' => NULL,
                'occurrence_number' => 37,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'charity_case_id' => 2,
                'assistance_type_id' => 3,
                'parent_schedule_id' => 11,
                'scheduled_date' => '2026-05-28',
                'end_date' => NULL,
                'occurrence_number' => 38,
                'scheduled_time' => NULL,
                'amount' => '1000.00',
                'quantity' => NULL,
                'frequency' => 'once',
                'status' => 'scheduled',
                'funding_status' => 'unfunded',
                'notes' => NULL,
                'created_at' => '2026-04-18 00:35:44',
                'updated_at' => '2026-04-18 00:35:44',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}