<?php

namespace App\Filament\Pages;

use App\Filament\Widgets\AssistanceCalendarWidget;
use BackedEnum;
use BezhanSalleh\FilamentShield\Traits\HasPageShield;
use Filament\Pages\Page;
use Filament\Support\Icons\Heroicon;
use Illuminate\Contracts\Support\Htmlable;

class AssistanceCalendar extends Page
{
    use HasPageShield;
    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedCalendarDays;

    protected static ?string $title = 'Assistance Calendar';

    protected static string|\UnitEnum|null $navigationGroup = 'Assistance';

    protected string $view = 'filament.pages.assistance-calendar';

    public function getTitle(): string|Htmlable
    {
        return __('Assistance Calendar'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationGroup(): ?string
    {
        return __('Assistance');
    }

    public static function getNavigationLabel(): string
    {
        return __('Assistance Calendar');
    }

    public function getHeaderWidgets(): array
    {
        return [
            AssistanceCalendarWidget::class,
        ];
    }

    public function getHeaderWidgetsColumns(): int|array
    {
        return 1;
    }
}
