<?php

namespace App\Filament\Pages;

use BezhanSalleh\FilamentShield\Traits\HasPanelShield;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Tabs;
use Filament\Schemas\Components\Tabs\Tab;
use Filament\Schemas\Schema;
use Illuminate\Contracts\Support\Htmlable;
use Outerweb\FilamentSettings\Pages\Settings;
use SalemAljebaly\FilamentMapPicker\MapPicker;
use Ysfkaya\FilamentPhoneInput\Forms\PhoneInput;

class SystemSettings extends Settings
{
    use HasPanelShield;
    public function getTitle(): string|Htmlable
    {
        return __('System Settings'); // TODO: Change the autogenerated stub
    }

    public static function getNavigationGroup(): ?string
    {
        return __('Settings');
    }

    public static function getNavigationLabel(): string
    {
        return __('System Settings');
    }
    public function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                Tabs::make()
                    ->columnSpanFull()
                    ->tabs([
                        Tab::make(__('General'))
                            ->schema([
                                TextInput::make('general.system_name')
                                    ->label(__('System Name'))
                                    ->required(),
                                Grid::make(2)->schema([
                                    PhoneInput::make('contact.primary_phone')
                                        ->label(__('Primary Phone')),
                                    PhoneInput::make('contact.secondary_phone')
                                        ->label(__('Secondary Phone')),
                                ]),
                                TextInput::make('contact.email')
                                    ->label(__('Email'))
                                    ->email(),
                                Textarea::make('contact.address')
                                    ->label(__('Address'))
                                    ->columnSpanFull(),
                                Hidden::make('contact.latitude')
                                    ->rules(['nullable', 'numeric']),
                                Hidden::make('contact.longitude')
                                    ->rules(['nullable', 'numeric']),
                                MapPicker::make('contact.location')
                                    ->label(__('Location'))
                                    ->latlngFields('contact.latitude', 'contact.longitude')
                                    ->searchable()
                                    ->collapsibleSearch()
                                    ->columnSpanFull()
                                    ->draggable(),
                            ]),
                        Tab::make(__('Branding'))
                            ->schema([
                                FileUpload::make('branding.logo')
                                    ->label(__('Logo'))
                                    ->image()
                                    ->directory('settings/branding')
                                    ->imageEditor(),
                                FileUpload::make('branding.favicon')
                                    ->label(__('Favicon'))
                                    ->image()
                                    ->directory('settings/branding')
                                    ->imageEditor(),
                            ]),
                        Tab::make(__('Media'))
                            ->schema([
                                FileUpload::make('media.hero_background_image')
                                    ->label(__('Hero Background Image'))
                                    ->image()
                                    ->directory('settings/media')
                                    ->imageEditor(),
                                FileUpload::make('media.about_image')
                                    ->label(__('About Image'))
                                    ->image()
                                    ->directory('settings/media')
                                    ->imageEditor(),
                            ]),
                    ]),
            ]);
    }
}
